name: mini_taskhub_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^3.1.2
  form_field_validator: ^1.1.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  provider: ^6.1.4
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
